#!/bin/bash

if [[ $1 == "--help" ]]; then
  echo "This program will rotate through all pictures (of cats) in the /home/pizza2d1/Downloads/catpics folder"
  exit
fi


CatPicturesArray=()
ls /home/pizza2d1/Downloads/catpics > tempcatfile.txt
CatList="tempcatfile.txt"
while read -r LINE; do
  if [[ $LINE == *".jpg"* || $LINE == *".jpeg"* || $LINE == *".png"* ]]; then
    CatPicturesArray+=("$LINE")
  fi
done  < $CatList

re='^[0-9]+$'
if [[ $1 =~ $re ]]; then
  sleepytime=$1
else
  sleepytime=1.5
fi

echo $1
echo $sleepytime

while true; do 
  for kitty in $(seq 0 $((${#CatPicturesArray[@]}-1))); do
    gsettings set org.gnome.desktop.background picture-uri "/home/pizza2d1/Downloads/catpics/${CatPicturesArray[$kitty]}"
    gsettings set org.gnome.desktop.background picture-uri-dark "/home/pizza2d1/Downloads/catpics/${CatPicturesArray[$kitty]}"
    sleep $sleepytime
  done
done
