#!/bin/bash

if [[ $1 == "--help" ]]; then
  echo "This program will convert all filenames in the current folder to lowercase letters and convert all spaces into undercases"
  exit
fi


for SRC in ./*;
do
    DST=`dirname "${SRC}"`/`basename "${SRC}" | tr '[A-Z]' '[a-z]'`
    if [ "${SRC}" != "${DST}" ]
    then
        [ ! -e "${DST}" ] && mv -T "${SRC}" "${DST}" || echo "${SRC} was not renamed"
    fi
done
for SRC in ./*;
do
    DST=`dirname "${SRC}"`/`basename "${SRC}" | tr ' ' '_'`
    if [ "${SRC}" != "${DST}" ]
    then
        [ ! -e "${DST}" ] && mv -T "${SRC}" "${DST}" || echo "${SRC} was not renamed"
    fi
done
