#!/bin/bash

DEFAULT_SHOW_NAME=$(basename $(pwd) | sed 's/Season.*//i')

read -p "What is the show's directory name?: " SHOW
read -p "What is the show name? (default: $DEFAULT_SHOW_NAME): " SHOW_NAME
if [[ -z $SHOW_NAME ]]; then
    SHOW_NAME=$DEFAULT_SHOW_NAME
# else
#     SHOW_NAME=$SHOW_NAME
fi
echo "<!DOCTYPE html>
<html lang=\"en-US\">
    <head>
        <title>$DISPLAY_NAME</title>
        <link rel=\"stylesheet\" href=\"/CSS/shows.css\">
        <link rel=\"stylesheet\" href=\"/CSS/buttons.css\">
        <link rel=\"stylesheet\" href=\"/CSS/tooltips.css\">
    </head>
    <body>
        <div id=\"HASH\" class=\"blue-msg\">
        <span id=\"time-HASH\" class=\"smalltext btn-square\"><a href=\"../index.html\">BACK</a></span>
        <span class=\"ios-circle btn-square\"><a href=\"/index.html\">HOMEPAGE</a></span>
        </div>" > index.html


read -p "How many seasons" SEASONS
for SEASON in $(seq $SEASONS); do

    echo "        <br>
        <h1>$DISPLAY_NAME Season $SEASON</h1>
        <p><a href=\"$SHOW""Season$SEASON/\">$DISPLAY_NAME Season $SEASON Downloads</a></p>" >> index.html

    read -p "How many episodes are in season $SEASON?: " EPISODES
    read -p "Do you want to include episode titles? [y/N]: " TITLE_CHOICE
    if [[ $TITLE_CHOICE == "y" ]] || [[ $TITLE_CHOICE == "Y" ]]; then
        read -p "Episode $EPISODE title: " EPISODE_TITLE 
        for EPISODE in $(seq $EPISODES); do
            echo "        <div class=\"button-container tooltip\">
            <h3><a href=\"stream_season$SEASON""_episode$EPISODE.html\" class=\"btn-square\">Episode $EPISODE</a></h3>
        <span class=\"tooltiptext\">$EPISODE_TITLE<img src=\"/assets/$SHOW/coverS$SEASON""E$EPISODE.jpeg\" alt=\"balls\"></span>
            </div>" >> index.html
        done
    else
        for EPISODE in $(seq $EPISODES); do
            echo "        <div class=\"button-container tooltip\">
            <h3><a href=\"stream_season$SEASON""_episode$EPISODE.html\" class=\"btn-square\">Episode $EPISODE</a></h3>
        <span class=\"tooltiptext\"><img src=\"/assets/$SHOW/coverS$SEASON""E$EPISODE.jpeg\" alt=\"balls\"></span>
            </div>" >> index.html
        done
    fi
done


# <!DOCTYPE html>
# <html lang=\"en-US\">
#     <head>
#         <title>$SHOW_PRETTY</title>
#         <link rel=\"stylesheet\" href=\"/CSS/shows.css\">
#         <link rel=\"stylesheet\" href=\"/CSS/buttons.css\">
#         <link rel=\"stylesheet\" href=\"/CSS/tooltips.css\">
#     </head>
#     <body>
#         <div id=\"HASH\" class=\"blue-msg\">
#         <span id=\"time-HASH\" class=\"smalltext btn-square\"><a href=\"../index.html\">BACK</a></span>
#         <span class=\"ios-circle btn-square\"><a href=\"/index.html\">HOMEPAGE</a></span>
#         </div>

#         <br>
#         <h1>$SHOW_PRETTY Season 1</h1>
#         <p><a href=\"$SHOWSeason1/\">$SHOW_PRETTY Season $SEASON Downloads</a></p>
#         <div class=\"button-container tooltip\">
#         <h3><a href=\"stream_season1_episode1.html\" class=\"btn-square\">Episode 1</a></h3>
# 		<span class=\"tooltiptext\"><img src=\"/assets/$SHOW/coverS1E1.jpeg\" alt=\"balls\"></span>
#         </div>
#         <div class=\"button-container tooltip\">
#         <h3><a href=\"stream_season1_episode2.html\" class=\"btn-square\">Episode 2</a></h3>
# 		<span class=\"tooltiptext\"><img src=\"/assets/$SHOW/coverS1E2.jpeg\" alt=\"balls\"></span>
#         </div>
#         <div class=\"button-container tooltip\">
#         <h3><a href=\"stream_season1_episode3.html\" class=\"btn-square\">Episode 3</a></h3>
# 		<span class=\"tooltiptext\"><img src=\"/assets/$SHOW/coverS1E3.jpeg\" alt=\"balls\"></span>
#         </div>
#         <div class=\"button-container tooltip\">
#         <h3><a href=\"stream_season1_episode4.html\" class=\"btn-square\">Episode 4</a></h3>
# 		<span class=\"tooltiptext\"><img src=\"/assets/$SHOW/coverS1E4.jpeg\" alt=\"balls\"></span>
#         </div>
#         <div class=\"button-container tooltip\">
#         <h3><a href=\"stream_season1_episode5.html\" class=\"btn-square\">Episode 5</a></h3>
# 		<span class=\"tooltiptext\"><img src=\"/assets/$SHOW/coverS1E5.jpeg\" alt=\"balls\"></span>
#         </div>
#         <div class=\"button-container tooltip\">
#         <h3><a href=\"stream_season1_episode6.html\" class=\"btn-square\">Episode 6</a></h3>
# 		<span class=\"tooltiptext\"><img src=\"/assets/$SHOW/coverS1E6.jpeg\" alt=\"balls\"></span>
#         </div>
#         <div class=\"button-container tooltip\">
#         <h3><a href=\"stream_season1_episode7.html\" class=\"btn-square\">Episode 7</a></h3>
# 		<span class=\"tooltiptext\"><img src=\"/assets/$SHOW/coverS1E7.jpeg\" alt=\"balls\"></span>
#         </div>
#         <div class=\"button-container tooltip\">
#         <h3><a href=\"stream_season1_episode8.html\" class=\"btn-square\">Episode 8</a></h3>
# 		<span class=\"tooltiptext\"><img src=\"/assets/$SHOW/coverS1E8.jpeg\" alt=\"balls\"></span>
#         </div>

#     </body>
# </html>
